feat: added logs options
yc-actions/yc-sls-function pull request #493
Opened 2023-10-06 20:06 UTC by 1xtr

Добавил опции для логирования.
Потестил локально на @yandex-cloud/nodejs-sdk

2023-10-09 08:02 UTC, nikolaymatrosov commented on src/main.ts
> +      logLevel: core.getInput('log-level', {required: false, trimWhitespace: true}) as LogLevelKeys,
Здесь стоило бы добавить парсинг и валидацию пользовательских значений. Как например, есть функция `parseMemory` для парсинга значений памяти.

2023-10-09 08:32 UTC, 1xtr commented on src/main.ts
> +      logLevel: core.getInput('log-level', {required: false, trimWhitespace: true}) as LogLevelKeys,
- `getBooleanInput` уже имеет свой валидатор.
 - для ID группы если только на длину строки валидатор добавить
 - на log level добавил

2023-10-09 10:33 UTC, nikolaymatrosov requested changes

2023-10-09 10:33 UTC, nikolaymatrosov commented on src/log-level.ts
> +  if (levelKey === undefined) {
`core.getInput` возвращает `string`. Там не может быть `undefined`. Нужны тесты на эту функцию.

2023-10-09 10:33 UTC, nikolaymatrosov commented on src/log-level.ts
> +export const parseLogLevel = (levelKey: LOG_LEVEL): number => {
Правильная сигнатура функции `parseLogLevel(levelKey: string): number`.
Хотя результирующий тип `number` можно сузить до `LogLevel_Level` отсюда `@yandex-cloud/nodejs-sdk/dist/generated/yandex/cloud/logging/v1/log_entry`.

Принимать на вход следует именно `string`, т.к. мы не можем знать, что пользователь не ошибся в параметрах.

2023-10-09 16:04 UTC, nikolaymatrosov commented on src/log-level.ts
> +  if (!Object.keys(LogLevel_Level).includes(levelKey.toUpperCase())) {
При такой реализации `UNRECOGNIZED` будет валидным входным параметром. А этого не хотелось бы. Я за явное перечисление валидных входных данных.

2023-10-09 16:05 UTC, 1xtr commented on src/log-level.ts
> +  if (!Object.keys(LogLevel_Level).includes(levelKey.toUpperCase())) {
понял, исправлю

2023-10-09 21:09 UTC, 1xtr commented on src/log-level.ts
> +  if (!Object.keys(LogLevel_Level).includes(levelKey.toUpperCase())) {
добавил

2023-10-10 12:11 UTC, nikolaymatrosov approved these changes

2023-10-10 12:11 UTC, merged