doc: service account invoker
yc-actions/yc-sls-function pull request #559
Opened 2024-01-01 20:18 UTC by gurza

2024-01-02 10:07 UTC, nikolaymatrosov requested changes

2024-01-02 10:07 UTC, nikolaymatrosov commented on README.md
> +`service-account` (optional) is the Service Account that invokes the serverless function.
That's wrong.

2024-01-02 10:07 UTC, nikolaymatrosov commented on action.yml
> +    description: 'Service account which can invoke function'
That's wrong.

2024-01-02 10:07 UTC, nikolaymatrosov commented on README.md
> +# GitHub Action to deploy Serverless Function to Yandex Cloud
I do not understand why this change is necessary.

2024-01-02 10:07 UTC, nikolaymatrosov commented on README.md
> +## Table of Contents
Please, leave the formatting as it is.

2024-01-04 20:17 UTC, gurza commented on README.md
> +# GitHub Action to deploy Serverless Function to Yandex Cloud
This is a non-critical change. I've fixed the linter's warning, https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md041.md. At your request, I've removed all changes to the README.md format from the PR.

2024-01-04 20:19 UTC, gurza commented on README.md
> +## Table of Contents
Sure. I've removed all changes to the README.md format from the PR.

2024-01-04 20:21 UTC, gurza commented on README.md
> +## Table of Contents
For your information. The linter returns a warning for this article https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md036.md

2024-01-04 21:12 UTC, gurza commented on action.yml
> +    description: 'Service account which can invoke function'
Let's figure out together why that's wrong.

The value of service-account is passed to the Function.createVersion request in the serviceAccountId parameter.

https://github.com/yc-actions/yc-sls-function/blob/ba73c799d12858e6280070424977517613b9efef/src/main.ts#L136

https://github.com/yc-actions/yc-sls-function/blob/ba73c799d12858e6280070424977517613b9efef/src/main.ts#L195

In the official documentation, https://cloud.yandex.com/en/docs/functions/functions/api-ref/Function/createVersion, it is stated that 
serviceAccountId is the ID of the service account to associate with the version.

I believe it is correct to say that it is the ID of the service account that is used to invoke the function. This will be clearer.  @nikolaymatrosov do you agree?

2024-01-04 21:22 UTC, nikolaymatrosov commented on action.yml
> +    description: 'Service account which can invoke function'
No. This service account **does not** invoke function. That's wrong.

2024-01-04 21:36 UTC, nikolaymatrosov commented on action.yml
> +    description: 'Service account which can invoke function'
If you want an example of a **service account that invokes function** you can find it in API Gateway. https://cloud.yandex.ru/en/docs/api-gateway/concepts/extensions/cloud-functions
There, you have to provide SA with role `functions.functionInvoker` to make it possible to invoke the function from API GW.

When you create a version of the function, you provide a service account whose IAM token will be available via metadata service. So, the function could perform actions on its behalf.

2024-01-04 22:23 UTC, gurza commented on action.yml
> +    description: 'Service account which can invoke function'
Thank you for the explanations. I will correct the description in the PR.

2024-01-05 11:42 UTC, closed without merging

2024-01-05 11:42 UTC, nikolaymatrosov commented
Thank you for dedicating your time to propose enhancements to our documentation and its code style. We greatly appreciate your initiative and the effort you've put into this pull request. However, after a detailed review, we've decided not to incorporate these changes. The current style and structure have been established to maintain consistency across our documentation. We truly value your contribution and encourage you to keep engaging with our project. Please feel free to reach out if you have further ideas or need any clarifications. Your involvement and understanding are immensely appreciated.